<?php
/**
 * Chat
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  TextMagic
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Textmagic API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.17.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace TextMagic\Models;

use \ArrayAccess;
use \TextMagic\ObjectSerializer;

/**
 * Chat Class Doc Comment
 *
 * @category Class
 * @package  TextMagic
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class Chat implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'Chat';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'id' => 'int',
        'originalId' => 'int',
        'phone' => 'string',
        'contact' => '\TextMagic\Models\Contact',
        'unsubscribedContactId' => 'int',
        'unread' => 'int',
        'updatedAt' => '\DateTime',
        'status' => 'string',
        'mute' => 'int',
        'lastMessage' => 'string',
        'direction' => 'string',
        'replyOptionsType' => 'string',
        'from' => 'string',
        'mutedUntil' => '\DateTime',
        'timeLeftMute' => 'int',
        'country' => '\TextMagic\Models\Country',
        'pinned' => 'bool',
        'type' => 'string',
        'smsPrice' => 'float',
        'mmsPrice' => 'float',
        'tags' => '\TextMagic\Models\Tag[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'id' => null,
        'originalId' => null,
        'phone' => null,
        'contact' => null,
        'unsubscribedContactId' => null,
        'unread' => null,
        'updatedAt' => 'date-time',
        'status' => null,
        'mute' => null,
        'lastMessage' => null,
        'direction' => null,
        'replyOptionsType' => null,
        'from' => null,
        'mutedUntil' => 'date-time',
        'timeLeftMute' => null,
        'country' => null,
        'pinned' => null,
        'type' => null,
        'smsPrice' => null,
        'mmsPrice' => null,
        'tags' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'id' => false,
        'originalId' => true,
        'phone' => false,
        'contact' => true,
        'unsubscribedContactId' => true,
        'unread' => false,
        'updatedAt' => false,
        'status' => false,
        'mute' => false,
        'lastMessage' => true,
        'direction' => true,
        'replyOptionsType' => true,
        'from' => true,
        'mutedUntil' => true,
        'timeLeftMute' => false,
        'country' => true,
        'pinned' => true,
        'type' => false,
        'smsPrice' => false,
        'mmsPrice' => false,
        'tags' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'id' => 'id',
        'originalId' => 'originalId',
        'phone' => 'phone',
        'contact' => 'contact',
        'unsubscribedContactId' => 'unsubscribedContactId',
        'unread' => 'unread',
        'updatedAt' => 'updatedAt',
        'status' => 'status',
        'mute' => 'mute',
        'lastMessage' => 'lastMessage',
        'direction' => 'direction',
        'replyOptionsType' => 'replyOptionsType',
        'from' => 'from',
        'mutedUntil' => 'mutedUntil',
        'timeLeftMute' => 'timeLeftMute',
        'country' => 'country',
        'pinned' => 'pinned',
        'type' => 'type',
        'smsPrice' => 'smsPrice',
        'mmsPrice' => 'mmsPrice',
        'tags' => 'tags'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'id' => 'setId',
        'originalId' => 'setOriginalId',
        'phone' => 'setPhone',
        'contact' => 'setContact',
        'unsubscribedContactId' => 'setUnsubscribedContactId',
        'unread' => 'setUnread',
        'updatedAt' => 'setUpdatedAt',
        'status' => 'setStatus',
        'mute' => 'setMute',
        'lastMessage' => 'setLastMessage',
        'direction' => 'setDirection',
        'replyOptionsType' => 'setReplyOptionsType',
        'from' => 'setFrom',
        'mutedUntil' => 'setMutedUntil',
        'timeLeftMute' => 'setTimeLeftMute',
        'country' => 'setCountry',
        'pinned' => 'setPinned',
        'type' => 'setType',
        'smsPrice' => 'setSmsPrice',
        'mmsPrice' => 'setMmsPrice',
        'tags' => 'setTags'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'id' => 'getId',
        'originalId' => 'getOriginalId',
        'phone' => 'getPhone',
        'contact' => 'getContact',
        'unsubscribedContactId' => 'getUnsubscribedContactId',
        'unread' => 'getUnread',
        'updatedAt' => 'getUpdatedAt',
        'status' => 'getStatus',
        'mute' => 'getMute',
        'lastMessage' => 'getLastMessage',
        'direction' => 'getDirection',
        'replyOptionsType' => 'getReplyOptionsType',
        'from' => 'getFrom',
        'mutedUntil' => 'getMutedUntil',
        'timeLeftMute' => 'getTimeLeftMute',
        'country' => 'getCountry',
        'pinned' => 'getPinned',
        'type' => 'getType',
        'smsPrice' => 'getSmsPrice',
        'mmsPrice' => 'getMmsPrice',
        'tags' => 'getTags'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const STATUS_A = 'a';
    public const STATUS_C = 'c';
    public const STATUS_D = 'd';
    public const DIRECTION_CI = 'ci';
    public const DIRECTION_CO = 'co';
    public const DIRECTION_I = 'i';
    public const DIRECTION_O = 'o';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getStatusAllowableValues()
    {
        return [
            self::STATUS_A,
            self::STATUS_C,
            self::STATUS_D,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getDirectionAllowableValues()
    {
        return [
            self::DIRECTION_CI,
            self::DIRECTION_CO,
            self::DIRECTION_I,
            self::DIRECTION_O,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('id', $data ?? [], null);
        $this->setIfExists('originalId', $data ?? [], null);
        $this->setIfExists('phone', $data ?? [], null);
        $this->setIfExists('contact', $data ?? [], null);
        $this->setIfExists('unsubscribedContactId', $data ?? [], null);
        $this->setIfExists('unread', $data ?? [], null);
        $this->setIfExists('updatedAt', $data ?? [], null);
        $this->setIfExists('status', $data ?? [], null);
        $this->setIfExists('mute', $data ?? [], null);
        $this->setIfExists('lastMessage', $data ?? [], null);
        $this->setIfExists('direction', $data ?? [], null);
        $this->setIfExists('replyOptionsType', $data ?? [], null);
        $this->setIfExists('from', $data ?? [], null);
        $this->setIfExists('mutedUntil', $data ?? [], null);
        $this->setIfExists('timeLeftMute', $data ?? [], null);
        $this->setIfExists('country', $data ?? [], null);
        $this->setIfExists('pinned', $data ?? [], null);
        $this->setIfExists('type', $data ?? [], null);
        $this->setIfExists('smsPrice', $data ?? [], null);
        $this->setIfExists('mmsPrice', $data ?? [], null);
        $this->setIfExists('tags', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['id'] === null) {
            $invalidProperties[] = "'id' can't be null";
        }
        if ($this->container['originalId'] === null) {
            $invalidProperties[] = "'originalId' can't be null";
        }
        if ($this->container['phone'] === null) {
            $invalidProperties[] = "'phone' can't be null";
        }
        if ($this->container['contact'] === null) {
            $invalidProperties[] = "'contact' can't be null";
        }
        if ($this->container['unsubscribedContactId'] === null) {
            $invalidProperties[] = "'unsubscribedContactId' can't be null";
        }
        if ($this->container['unread'] === null) {
            $invalidProperties[] = "'unread' can't be null";
        }
        if ($this->container['updatedAt'] === null) {
            $invalidProperties[] = "'updatedAt' can't be null";
        }
        if ($this->container['status'] === null) {
            $invalidProperties[] = "'status' can't be null";
        }
        $allowedValues = $this->getStatusAllowableValues();
        if (!is_null($this->container['status']) && !in_array($this->container['status'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'status', must be one of '%s'",
                $this->container['status'],
                implode("', '", $allowedValues)
            );
        }

        if ($this->container['mute'] === null) {
            $invalidProperties[] = "'mute' can't be null";
        }
        if ($this->container['lastMessage'] === null) {
            $invalidProperties[] = "'lastMessage' can't be null";
        }
        if ($this->container['direction'] === null) {
            $invalidProperties[] = "'direction' can't be null";
        }
        $allowedValues = $this->getDirectionAllowableValues();
        if (!is_null($this->container['direction']) && !in_array($this->container['direction'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'direction', must be one of '%s'",
                $this->container['direction'],
                implode("', '", $allowedValues)
            );
        }

        if ($this->container['replyOptionsType'] === null) {
            $invalidProperties[] = "'replyOptionsType' can't be null";
        }
        if ($this->container['from'] === null) {
            $invalidProperties[] = "'from' can't be null";
        }
        if ($this->container['mutedUntil'] === null) {
            $invalidProperties[] = "'mutedUntil' can't be null";
        }
        if ($this->container['timeLeftMute'] === null) {
            $invalidProperties[] = "'timeLeftMute' can't be null";
        }
        if ($this->container['country'] === null) {
            $invalidProperties[] = "'country' can't be null";
        }
        if ($this->container['pinned'] === null) {
            $invalidProperties[] = "'pinned' can't be null";
        }
        if ($this->container['type'] === null) {
            $invalidProperties[] = "'type' can't be null";
        }
        if ($this->container['smsPrice'] === null) {
            $invalidProperties[] = "'smsPrice' can't be null";
        }
        if ($this->container['mmsPrice'] === null) {
            $invalidProperties[] = "'mmsPrice' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets id
     *
     * @return int
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param int $id Chat ID.
     *
     * @return self
     */
    public function setId($id)
    {
        if (is_null($id)) {
            throw new \InvalidArgumentException('non-nullable id cannot be null');
        }
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets originalId
     *
     * @return int
     */
    public function getOriginalId()
    {
        return $this->container['originalId'];
    }

    /**
     * Sets originalId
     *
     * @param int $originalId originalId
     *
     * @return self
     */
    public function setOriginalId($originalId)
    {
        if (is_null($originalId)) {
            array_push($this->openAPINullablesSetToNull, 'originalId');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('originalId', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['originalId'] = $originalId;

        return $this;
    }

    /**
     * Gets phone
     *
     * @return string
     */
    public function getPhone()
    {
        return $this->container['phone'];
    }

    /**
     * Sets phone
     *
     * @param string $phone Chat partner's phone number.
     *
     * @return self
     */
    public function setPhone($phone)
    {
        if (is_null($phone)) {
            throw new \InvalidArgumentException('non-nullable phone cannot be null');
        }
        $this->container['phone'] = $phone;

        return $this;
    }

    /**
     * Gets contact
     *
     * @return \TextMagic\Models\Contact
     */
    public function getContact()
    {
        return $this->container['contact'];
    }

    /**
     * Sets contact
     *
     * @param \TextMagic\Models\Contact $contact contact
     *
     * @return self
     */
    public function setContact($contact)
    {
        if (is_null($contact)) {
            array_push($this->openAPINullablesSetToNull, 'contact');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('contact', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['contact'] = $contact;

        return $this;
    }

    /**
     * Gets unsubscribedContactId
     *
     * @return int
     */
    public function getUnsubscribedContactId()
    {
        return $this->container['unsubscribedContactId'];
    }

    /**
     * Sets unsubscribedContactId
     *
     * @param int $unsubscribedContactId If this field has a value, it means that the chat phone number has been unsubscribed from you and this value is an ID of an Unsubscribed contact entity. See [Get all unsubscribed contacts](https://docs.textmagic.com/#operation/getUnsubscribers).
     *
     * @return self
     */
    public function setUnsubscribedContactId($unsubscribedContactId)
    {
        if (is_null($unsubscribedContactId)) {
            array_push($this->openAPINullablesSetToNull, 'unsubscribedContactId');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('unsubscribedContactId', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['unsubscribedContactId'] = $unsubscribedContactId;

        return $this;
    }

    /**
     * Gets unread
     *
     * @return int
     */
    public function getUnread()
    {
        return $this->container['unread'];
    }

    /**
     * Sets unread
     *
     * @param int $unread Total unread incoming messages.
     *
     * @return self
     */
    public function setUnread($unread)
    {
        if (is_null($unread)) {
            throw new \InvalidArgumentException('non-nullable unread cannot be null');
        }
        $this->container['unread'] = $unread;

        return $this;
    }

    /**
     * Gets updatedAt
     *
     * @return \DateTime
     */
    public function getUpdatedAt()
    {
        return $this->container['updatedAt'];
    }

    /**
     * Sets updatedAt
     *
     * @param \DateTime $updatedAt Time when the last incoming message arrived at this chat.
     *
     * @return self
     */
    public function setUpdatedAt($updatedAt)
    {
        if (is_null($updatedAt)) {
            throw new \InvalidArgumentException('non-nullable updatedAt cannot be null');
        }
        $this->container['updatedAt'] = $updatedAt;

        return $this;
    }

    /**
     * Gets status
     *
     * @return string
     */
    public function getStatus()
    {
        return $this->container['status'];
    }

    /**
     * Sets status
     *
     * @param string $status Chat status:   * **a** - Active;   * **c** - Closed;   * **d** - Deleted.
     *
     * @return self
     */
    public function setStatus($status)
    {
        if (is_null($status)) {
            throw new \InvalidArgumentException('non-nullable status cannot be null');
        }
        $allowedValues = $this->getStatusAllowableValues();
        if (!in_array($status, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'status', must be one of '%s'",
                    $status,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['status'] = $status;

        return $this;
    }

    /**
     * Gets mute
     *
     * @return int
     */
    public function getMute()
    {
        return $this->container['mute'];
    }

    /**
     * Sets mute
     *
     * @param int $mute Indicates when the chat is muted.
     *
     * @return self
     */
    public function setMute($mute)
    {
        if (is_null($mute)) {
            throw new \InvalidArgumentException('non-nullable mute cannot be null');
        }
        $this->container['mute'] = $mute;

        return $this;
    }

    /**
     * Gets lastMessage
     *
     * @return string
     */
    public function getLastMessage()
    {
        return $this->container['lastMessage'];
    }

    /**
     * Sets lastMessage
     *
     * @param string $lastMessage The last message content of a chat.
     *
     * @return self
     */
    public function setLastMessage($lastMessage)
    {
        if (is_null($lastMessage)) {
            array_push($this->openAPINullablesSetToNull, 'lastMessage');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('lastMessage', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['lastMessage'] = $lastMessage;

        return $this;
    }

    /**
     * Gets direction
     *
     * @return string
     */
    public function getDirection()
    {
        return $this->container['direction'];
    }

    /**
     * Sets direction
     *
     * @param string $direction Last message type: * **ci** - incoming call; * **co** - outgoing call; * **i** - incoming message; * **o** - outgoing message.
     *
     * @return self
     */
    public function setDirection($direction)
    {
        if (is_null($direction)) {
            array_push($this->openAPINullablesSetToNull, 'direction');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('direction', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $allowedValues = $this->getDirectionAllowableValues();
        if (!is_null($direction) && !in_array($direction, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'direction', must be one of '%s'",
                    $direction,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['direction'] = $direction;

        return $this;
    }

    /**
     * Gets replyOptionsType
     *
     * @return string
     */
    public function getReplyOptionsType()
    {
        return $this->container['replyOptionsType'];
    }

    /**
     * Sets replyOptionsType
     *
     * @param string $replyOptionsType Used for chats prices.
     *
     * @return self
     */
    public function setReplyOptionsType($replyOptionsType)
    {
        if (is_null($replyOptionsType)) {
            array_push($this->openAPINullablesSetToNull, 'replyOptionsType');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('replyOptionsType', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['replyOptionsType'] = $replyOptionsType;

        return $this;
    }

    /**
     * Gets from
     *
     * @return string
     */
    public function getFrom()
    {
        return $this->container['from'];
    }

    /**
     * Sets from
     *
     * @param string $from If filled, the value will be used as a sender number for all outgoing messages of a chat.
     *
     * @return self
     */
    public function setFrom($from)
    {
        if (is_null($from)) {
            array_push($this->openAPINullablesSetToNull, 'from');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('from', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['from'] = $from;

        return $this;
    }

    /**
     * Gets mutedUntil
     *
     * @return \DateTime
     */
    public function getMutedUntil()
    {
        return $this->container['mutedUntil'];
    }

    /**
     * Sets mutedUntil
     *
     * @param \DateTime $mutedUntil Date and time until the chat will be muted.
     *
     * @return self
     */
    public function setMutedUntil($mutedUntil)
    {
        if (is_null($mutedUntil)) {
            array_push($this->openAPINullablesSetToNull, 'mutedUntil');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('mutedUntil', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['mutedUntil'] = $mutedUntil;

        return $this;
    }

    /**
     * Gets timeLeftMute
     *
     * @return int
     */
    public function getTimeLeftMute()
    {
        return $this->container['timeLeftMute'];
    }

    /**
     * Sets timeLeftMute
     *
     * @param int $timeLeftMute Time left untill the chat will be unmuted (seconds).
     *
     * @return self
     */
    public function setTimeLeftMute($timeLeftMute)
    {
        if (is_null($timeLeftMute)) {
            throw new \InvalidArgumentException('non-nullable timeLeftMute cannot be null');
        }
        $this->container['timeLeftMute'] = $timeLeftMute;

        return $this;
    }

    /**
     * Gets country
     *
     * @return \TextMagic\Models\Country
     */
    public function getCountry()
    {
        return $this->container['country'];
    }

    /**
     * Sets country
     *
     * @param \TextMagic\Models\Country $country country
     *
     * @return self
     */
    public function setCountry($country)
    {
        if (is_null($country)) {
            array_push($this->openAPINullablesSetToNull, 'country');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('country', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['country'] = $country;

        return $this;
    }

    /**
     * Gets pinned
     *
     * @return bool
     */
    public function getPinned()
    {
        return $this->container['pinned'];
    }

    /**
     * Sets pinned
     *
     * @param bool $pinned Indicates when the chat is pinned.
     *
     * @return self
     */
    public function setPinned($pinned)
    {
        if (is_null($pinned)) {
            array_push($this->openAPINullablesSetToNull, 'pinned');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('pinned', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['pinned'] = $pinned;

        return $this;
    }

    /**
     * Gets type
     *
     * @return string
     */
    public function getType()
    {
        return $this->container['type'];
    }

    /**
     * Sets type
     *
     * @param string $type Chat type.
     *
     * @return self
     */
    public function setType($type)
    {
        if (is_null($type)) {
            throw new \InvalidArgumentException('non-nullable type cannot be null');
        }
        $this->container['type'] = $type;

        return $this;
    }

    /**
     * Gets smsPrice
     *
     * @return float
     */
    public function getSmsPrice()
    {
        return $this->container['smsPrice'];
    }

    /**
     * Sets smsPrice
     *
     * @param float $smsPrice smsPrice
     *
     * @return self
     */
    public function setSmsPrice($smsPrice)
    {
        if (is_null($smsPrice)) {
            throw new \InvalidArgumentException('non-nullable smsPrice cannot be null');
        }
        $this->container['smsPrice'] = $smsPrice;

        return $this;
    }

    /**
     * Gets mmsPrice
     *
     * @return float
     */
    public function getMmsPrice()
    {
        return $this->container['mmsPrice'];
    }

    /**
     * Sets mmsPrice
     *
     * @param float $mmsPrice mmsPrice
     *
     * @return self
     */
    public function setMmsPrice($mmsPrice)
    {
        if (is_null($mmsPrice)) {
            throw new \InvalidArgumentException('non-nullable mmsPrice cannot be null');
        }
        $this->container['mmsPrice'] = $mmsPrice;

        return $this;
    }

    /**
     * Gets tags
     *
     * @return \TextMagic\Models\Tag[]|null
     */
    public function getTags()
    {
        return $this->container['tags'];
    }

    /**
     * Sets tags
     *
     * @param \TextMagic\Models\Tag[]|null $tags tags
     *
     * @return self
     */
    public function setTags($tags)
    {
        if (is_null($tags)) {
            throw new \InvalidArgumentException('non-nullable tags cannot be null');
        }
        $this->container['tags'] = $tags;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


