<?php
/**
 * GetInboundMessagesNotificationSettingsResponse
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  TextMagic
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Textmagic API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.17.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace TextMagic\Models;

use \ArrayAccess;
use \TextMagic\ObjectSerializer;

/**
 * GetInboundMessagesNotificationSettingsResponse Class Doc Comment
 *
 * @category Class
 * @package  TextMagic
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class GetInboundMessagesNotificationSettingsResponse implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'GetInboundMessagesNotificationSettingsResponse';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'inboundMessageNotification' => 'bool',
        'forwardedCallNotification' => 'bool',
        'includeSmsHistory' => 'bool',
        'sendInHtmlFormat' => 'bool',
        'alertEmail1' => 'string',
        'alertEmail2' => 'string',
        'alertEmail3' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'inboundMessageNotification' => null,
        'forwardedCallNotification' => null,
        'includeSmsHistory' => null,
        'sendInHtmlFormat' => null,
        'alertEmail1' => null,
        'alertEmail2' => null,
        'alertEmail3' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'inboundMessageNotification' => false,
        'forwardedCallNotification' => false,
        'includeSmsHistory' => false,
        'sendInHtmlFormat' => false,
        'alertEmail1' => false,
        'alertEmail2' => false,
        'alertEmail3' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'inboundMessageNotification' => 'inboundMessageNotification',
        'forwardedCallNotification' => 'forwardedCallNotification',
        'includeSmsHistory' => 'includeSmsHistory',
        'sendInHtmlFormat' => 'sendInHtmlFormat',
        'alertEmail1' => 'alertEmail1',
        'alertEmail2' => 'alertEmail2',
        'alertEmail3' => 'alertEmail3'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'inboundMessageNotification' => 'setInboundMessageNotification',
        'forwardedCallNotification' => 'setForwardedCallNotification',
        'includeSmsHistory' => 'setIncludeSmsHistory',
        'sendInHtmlFormat' => 'setSendInHtmlFormat',
        'alertEmail1' => 'setAlertEmail1',
        'alertEmail2' => 'setAlertEmail2',
        'alertEmail3' => 'setAlertEmail3'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'inboundMessageNotification' => 'getInboundMessageNotification',
        'forwardedCallNotification' => 'getForwardedCallNotification',
        'includeSmsHistory' => 'getIncludeSmsHistory',
        'sendInHtmlFormat' => 'getSendInHtmlFormat',
        'alertEmail1' => 'getAlertEmail1',
        'alertEmail2' => 'getAlertEmail2',
        'alertEmail3' => 'getAlertEmail3'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('inboundMessageNotification', $data ?? [], null);
        $this->setIfExists('forwardedCallNotification', $data ?? [], null);
        $this->setIfExists('includeSmsHistory', $data ?? [], null);
        $this->setIfExists('sendInHtmlFormat', $data ?? [], null);
        $this->setIfExists('alertEmail1', $data ?? [], null);
        $this->setIfExists('alertEmail2', $data ?? [], null);
        $this->setIfExists('alertEmail3', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['inboundMessageNotification'] === null) {
            $invalidProperties[] = "'inboundMessageNotification' can't be null";
        }
        if ($this->container['forwardedCallNotification'] === null) {
            $invalidProperties[] = "'forwardedCallNotification' can't be null";
        }
        if ($this->container['includeSmsHistory'] === null) {
            $invalidProperties[] = "'includeSmsHistory' can't be null";
        }
        if ($this->container['sendInHtmlFormat'] === null) {
            $invalidProperties[] = "'sendInHtmlFormat' can't be null";
        }
        if ($this->container['alertEmail1'] === null) {
            $invalidProperties[] = "'alertEmail1' can't be null";
        }
        if ($this->container['alertEmail2'] === null) {
            $invalidProperties[] = "'alertEmail2' can't be null";
        }
        if ($this->container['alertEmail3'] === null) {
            $invalidProperties[] = "'alertEmail3' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets inboundMessageNotification
     *
     * @return bool
     */
    public function getInboundMessageNotification()
    {
        return $this->container['inboundMessageNotification'];
    }

    /**
     * Sets inboundMessageNotification
     *
     * @param bool $inboundMessageNotification Should user receive notification about new incoming messages.
     *
     * @return self
     */
    public function setInboundMessageNotification($inboundMessageNotification)
    {
        if (is_null($inboundMessageNotification)) {
            throw new \InvalidArgumentException('non-nullable inboundMessageNotification cannot be null');
        }
        $this->container['inboundMessageNotification'] = $inboundMessageNotification;

        return $this;
    }

    /**
     * Gets forwardedCallNotification
     *
     * @return bool
     */
    public function getForwardedCallNotification()
    {
        return $this->container['forwardedCallNotification'];
    }

    /**
     * Sets forwardedCallNotification
     *
     * @param bool $forwardedCallNotification Should user receive notification about new forwarded calls.
     *
     * @return self
     */
    public function setForwardedCallNotification($forwardedCallNotification)
    {
        if (is_null($forwardedCallNotification)) {
            throw new \InvalidArgumentException('non-nullable forwardedCallNotification cannot be null');
        }
        $this->container['forwardedCallNotification'] = $forwardedCallNotification;

        return $this;
    }

    /**
     * Gets includeSmsHistory
     *
     * @return bool
     */
    public function getIncludeSmsHistory()
    {
        return $this->container['includeSmsHistory'];
    }

    /**
     * Sets includeSmsHistory
     *
     * @param bool $includeSmsHistory Include SMS history into notification Email.
     *
     * @return self
     */
    public function setIncludeSmsHistory($includeSmsHistory)
    {
        if (is_null($includeSmsHistory)) {
            throw new \InvalidArgumentException('non-nullable includeSmsHistory cannot be null');
        }
        $this->container['includeSmsHistory'] = $includeSmsHistory;

        return $this;
    }

    /**
     * Gets sendInHtmlFormat
     *
     * @return bool
     */
    public function getSendInHtmlFormat()
    {
        return $this->container['sendInHtmlFormat'];
    }

    /**
     * Sets sendInHtmlFormat
     *
     * @param bool $sendInHtmlFormat Send Email notification in HTML format.
     *
     * @return self
     */
    public function setSendInHtmlFormat($sendInHtmlFormat)
    {
        if (is_null($sendInHtmlFormat)) {
            throw new \InvalidArgumentException('non-nullable sendInHtmlFormat cannot be null');
        }
        $this->container['sendInHtmlFormat'] = $sendInHtmlFormat;

        return $this;
    }

    /**
     * Gets alertEmail1
     *
     * @return string
     */
    public function getAlertEmail1()
    {
        return $this->container['alertEmail1'];
    }

    /**
     * Sets alertEmail1
     *
     * @param string $alertEmail1 New message notification email 1.
     *
     * @return self
     */
    public function setAlertEmail1($alertEmail1)
    {
        if (is_null($alertEmail1)) {
            throw new \InvalidArgumentException('non-nullable alertEmail1 cannot be null');
        }
        $this->container['alertEmail1'] = $alertEmail1;

        return $this;
    }

    /**
     * Gets alertEmail2
     *
     * @return string
     */
    public function getAlertEmail2()
    {
        return $this->container['alertEmail2'];
    }

    /**
     * Sets alertEmail2
     *
     * @param string $alertEmail2 New message notification email 2.
     *
     * @return self
     */
    public function setAlertEmail2($alertEmail2)
    {
        if (is_null($alertEmail2)) {
            throw new \InvalidArgumentException('non-nullable alertEmail2 cannot be null');
        }
        $this->container['alertEmail2'] = $alertEmail2;

        return $this;
    }

    /**
     * Gets alertEmail3
     *
     * @return string
     */
    public function getAlertEmail3()
    {
        return $this->container['alertEmail3'];
    }

    /**
     * Sets alertEmail3
     *
     * @param string $alertEmail3 New message notification email 3.
     *
     * @return self
     */
    public function setAlertEmail3($alertEmail3)
    {
        if (is_null($alertEmail3)) {
            throw new \InvalidArgumentException('non-nullable alertEmail3 cannot be null');
        }
        $this->container['alertEmail3'] = $alertEmail3;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


