<?php
/**
 * OutboundEmailResponse
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  TextMagic
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Textmagic API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.17.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace TextMagic\Models;

use \ArrayAccess;
use \TextMagic\ObjectSerializer;

/**
 * OutboundEmailResponse Class Doc Comment
 *
 * @category Class
 * @package  TextMagic
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class OutboundEmailResponse implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'OutboundEmailResponse';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'id' => 'int',
        'sendTime' => '\DateTime',
        'fromName' => 'string',
        'fromEmail' => 'string',
        'replyToEmail' => 'string',
        'recipientFullName' => 'string',
        'recipientEmail' => 'string',
        'emailSubject' => 'string',
        'emailContent' => 'string',
        'source' => 'string',
        'status' => 'string',
        'cost' => 'float',
        'statusReason' => 'string',
        'contactId' => 'int',
        'initiatorId' => 'int'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'id' => null,
        'sendTime' => 'date-time',
        'fromName' => null,
        'fromEmail' => 'email',
        'replyToEmail' => 'email',
        'recipientFullName' => null,
        'recipientEmail' => 'email',
        'emailSubject' => null,
        'emailContent' => null,
        'source' => null,
        'status' => null,
        'cost' => 'float',
        'statusReason' => null,
        'contactId' => null,
        'initiatorId' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'id' => false,
        'sendTime' => false,
        'fromName' => true,
        'fromEmail' => false,
        'replyToEmail' => false,
        'recipientFullName' => true,
        'recipientEmail' => true,
        'emailSubject' => false,
        'emailContent' => false,
        'source' => false,
        'status' => false,
        'cost' => false,
        'statusReason' => true,
        'contactId' => true,
        'initiatorId' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'id' => 'id',
        'sendTime' => 'sendTime',
        'fromName' => 'fromName',
        'fromEmail' => 'fromEmail',
        'replyToEmail' => 'replyToEmail',
        'recipientFullName' => 'recipientFullName',
        'recipientEmail' => 'recipientEmail',
        'emailSubject' => 'emailSubject',
        'emailContent' => 'emailContent',
        'source' => 'source',
        'status' => 'status',
        'cost' => 'cost',
        'statusReason' => 'statusReason',
        'contactId' => 'contactId',
        'initiatorId' => 'initiatorId'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'id' => 'setId',
        'sendTime' => 'setSendTime',
        'fromName' => 'setFromName',
        'fromEmail' => 'setFromEmail',
        'replyToEmail' => 'setReplyToEmail',
        'recipientFullName' => 'setRecipientFullName',
        'recipientEmail' => 'setRecipientEmail',
        'emailSubject' => 'setEmailSubject',
        'emailContent' => 'setEmailContent',
        'source' => 'setSource',
        'status' => 'setStatus',
        'cost' => 'setCost',
        'statusReason' => 'setStatusReason',
        'contactId' => 'setContactId',
        'initiatorId' => 'setInitiatorId'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'id' => 'getId',
        'sendTime' => 'getSendTime',
        'fromName' => 'getFromName',
        'fromEmail' => 'getFromEmail',
        'replyToEmail' => 'getReplyToEmail',
        'recipientFullName' => 'getRecipientFullName',
        'recipientEmail' => 'getRecipientEmail',
        'emailSubject' => 'getEmailSubject',
        'emailContent' => 'getEmailContent',
        'source' => 'getSource',
        'status' => 'getStatus',
        'cost' => 'getCost',
        'statusReason' => 'getStatusReason',
        'contactId' => 'getContactId',
        'initiatorId' => 'getInitiatorId'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const SOURCE_EMAIL_CAMPAIGN = 'emailCampaign';
    public const SOURCE_TICKET = 'ticket';
    public const STATUS_PENDING = 'pending';
    public const STATUS_SENT = 'sent';
    public const STATUS_DELIVERED = 'delivered';
    public const STATUS_REJECTED = 'rejected';
    public const STATUS_FAILED = 'failed';
    public const STATUS_OPENED = 'opened';
    public const STATUS_CLICKED = 'clicked';
    public const STATUS_UNSUBSCRIBED = 'unsubscribed';
    public const STATUS_SPAM = 'spam';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getSourceAllowableValues()
    {
        return [
            self::SOURCE_EMAIL_CAMPAIGN,
            self::SOURCE_TICKET,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getStatusAllowableValues()
    {
        return [
            self::STATUS_PENDING,
            self::STATUS_SENT,
            self::STATUS_DELIVERED,
            self::STATUS_REJECTED,
            self::STATUS_FAILED,
            self::STATUS_OPENED,
            self::STATUS_CLICKED,
            self::STATUS_UNSUBSCRIBED,
            self::STATUS_SPAM,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('id', $data ?? [], null);
        $this->setIfExists('sendTime', $data ?? [], null);
        $this->setIfExists('fromName', $data ?? [], null);
        $this->setIfExists('fromEmail', $data ?? [], null);
        $this->setIfExists('replyToEmail', $data ?? [], null);
        $this->setIfExists('recipientFullName', $data ?? [], null);
        $this->setIfExists('recipientEmail', $data ?? [], null);
        $this->setIfExists('emailSubject', $data ?? [], null);
        $this->setIfExists('emailContent', $data ?? [], null);
        $this->setIfExists('source', $data ?? [], null);
        $this->setIfExists('status', $data ?? [], null);
        $this->setIfExists('cost', $data ?? [], null);
        $this->setIfExists('statusReason', $data ?? [], null);
        $this->setIfExists('contactId', $data ?? [], null);
        $this->setIfExists('initiatorId', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['id'] === null) {
            $invalidProperties[] = "'id' can't be null";
        }
        if ($this->container['sendTime'] === null) {
            $invalidProperties[] = "'sendTime' can't be null";
        }
        if ($this->container['fromEmail'] === null) {
            $invalidProperties[] = "'fromEmail' can't be null";
        }
        if ($this->container['replyToEmail'] === null) {
            $invalidProperties[] = "'replyToEmail' can't be null";
        }
        if ($this->container['emailSubject'] === null) {
            $invalidProperties[] = "'emailSubject' can't be null";
        }
        if ($this->container['emailContent'] === null) {
            $invalidProperties[] = "'emailContent' can't be null";
        }
        if ($this->container['source'] === null) {
            $invalidProperties[] = "'source' can't be null";
        }
        $allowedValues = $this->getSourceAllowableValues();
        if (!is_null($this->container['source']) && !in_array($this->container['source'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'source', must be one of '%s'",
                $this->container['source'],
                implode("', '", $allowedValues)
            );
        }

        if ($this->container['status'] === null) {
            $invalidProperties[] = "'status' can't be null";
        }
        $allowedValues = $this->getStatusAllowableValues();
        if (!is_null($this->container['status']) && !in_array($this->container['status'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'status', must be one of '%s'",
                $this->container['status'],
                implode("', '", $allowedValues)
            );
        }

        if ($this->container['cost'] === null) {
            $invalidProperties[] = "'cost' can't be null";
        }
        if ($this->container['initiatorId'] === null) {
            $invalidProperties[] = "'initiatorId' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets id
     *
     * @return int
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param int $id Outbound email ID.
     *
     * @return self
     */
    public function setId($id)
    {
        if (is_null($id)) {
            throw new \InvalidArgumentException('non-nullable id cannot be null');
        }
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets sendTime
     *
     * @return \DateTime
     */
    public function getSendTime()
    {
        return $this->container['sendTime'];
    }

    /**
     * Sets sendTime
     *
     * @param \DateTime $sendTime Email send timestamp.
     *
     * @return self
     */
    public function setSendTime($sendTime)
    {
        if (is_null($sendTime)) {
            throw new \InvalidArgumentException('non-nullable sendTime cannot be null');
        }
        $this->container['sendTime'] = $sendTime;

        return $this;
    }

    /**
     * Gets fromName
     *
     * @return string|null
     */
    public function getFromName()
    {
        return $this->container['fromName'];
    }

    /**
     * Sets fromName
     *
     * @param string|null $fromName Sender name.
     *
     * @return self
     */
    public function setFromName($fromName)
    {
        if (is_null($fromName)) {
            array_push($this->openAPINullablesSetToNull, 'fromName');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('fromName', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['fromName'] = $fromName;

        return $this;
    }

    /**
     * Gets fromEmail
     *
     * @return string
     */
    public function getFromEmail()
    {
        return $this->container['fromEmail'];
    }

    /**
     * Sets fromEmail
     *
     * @param string $fromEmail Sender email address.
     *
     * @return self
     */
    public function setFromEmail($fromEmail)
    {
        if (is_null($fromEmail)) {
            throw new \InvalidArgumentException('non-nullable fromEmail cannot be null');
        }
        $this->container['fromEmail'] = $fromEmail;

        return $this;
    }

    /**
     * Gets replyToEmail
     *
     * @return string
     */
    public function getReplyToEmail()
    {
        return $this->container['replyToEmail'];
    }

    /**
     * Sets replyToEmail
     *
     * @param string $replyToEmail Reply-to email address.
     *
     * @return self
     */
    public function setReplyToEmail($replyToEmail)
    {
        if (is_null($replyToEmail)) {
            throw new \InvalidArgumentException('non-nullable replyToEmail cannot be null');
        }
        $this->container['replyToEmail'] = $replyToEmail;

        return $this;
    }

    /**
     * Gets recipientFullName
     *
     * @return string|null
     */
    public function getRecipientFullName()
    {
        return $this->container['recipientFullName'];
    }

    /**
     * Sets recipientFullName
     *
     * @param string|null $recipientFullName Recipient's full name.
     *
     * @return self
     */
    public function setRecipientFullName($recipientFullName)
    {
        if (is_null($recipientFullName)) {
            array_push($this->openAPINullablesSetToNull, 'recipientFullName');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('recipientFullName', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['recipientFullName'] = $recipientFullName;

        return $this;
    }

    /**
     * Gets recipientEmail
     *
     * @return string|null
     */
    public function getRecipientEmail()
    {
        return $this->container['recipientEmail'];
    }

    /**
     * Sets recipientEmail
     *
     * @param string|null $recipientEmail Recipient's email address.
     *
     * @return self
     */
    public function setRecipientEmail($recipientEmail)
    {
        if (is_null($recipientEmail)) {
            array_push($this->openAPINullablesSetToNull, 'recipientEmail');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('recipientEmail', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['recipientEmail'] = $recipientEmail;

        return $this;
    }

    /**
     * Gets emailSubject
     *
     * @return string
     */
    public function getEmailSubject()
    {
        return $this->container['emailSubject'];
    }

    /**
     * Sets emailSubject
     *
     * @param string $emailSubject Email subject line.
     *
     * @return self
     */
    public function setEmailSubject($emailSubject)
    {
        if (is_null($emailSubject)) {
            throw new \InvalidArgumentException('non-nullable emailSubject cannot be null');
        }
        $this->container['emailSubject'] = $emailSubject;

        return $this;
    }

    /**
     * Gets emailContent
     *
     * @return string
     */
    public function getEmailContent()
    {
        return $this->container['emailContent'];
    }

    /**
     * Sets emailContent
     *
     * @param string $emailContent HTML email content.
     *
     * @return self
     */
    public function setEmailContent($emailContent)
    {
        if (is_null($emailContent)) {
            throw new \InvalidArgumentException('non-nullable emailContent cannot be null');
        }
        $this->container['emailContent'] = $emailContent;

        return $this;
    }

    /**
     * Gets source
     *
     * @return string
     */
    public function getSource()
    {
        return $this->container['source'];
    }

    /**
     * Sets source
     *
     * @param string $source Source of the outbound email.
     *
     * @return self
     */
    public function setSource($source)
    {
        if (is_null($source)) {
            throw new \InvalidArgumentException('non-nullable source cannot be null');
        }
        $allowedValues = $this->getSourceAllowableValues();
        if (!in_array($source, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'source', must be one of '%s'",
                    $source,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['source'] = $source;

        return $this;
    }

    /**
     * Gets status
     *
     * @return string
     */
    public function getStatus()
    {
        return $this->container['status'];
    }

    /**
     * Sets status
     *
     * @param string $status Current email status.
     *
     * @return self
     */
    public function setStatus($status)
    {
        if (is_null($status)) {
            throw new \InvalidArgumentException('non-nullable status cannot be null');
        }
        $allowedValues = $this->getStatusAllowableValues();
        if (!in_array($status, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'status', must be one of '%s'",
                    $status,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['status'] = $status;

        return $this;
    }

    /**
     * Gets cost
     *
     * @return float
     */
    public function getCost()
    {
        return $this->container['cost'];
    }

    /**
     * Sets cost
     *
     * @param float $cost Cost of sending this email.
     *
     * @return self
     */
    public function setCost($cost)
    {
        if (is_null($cost)) {
            throw new \InvalidArgumentException('non-nullable cost cannot be null');
        }
        $this->container['cost'] = $cost;

        return $this;
    }

    /**
     * Gets statusReason
     *
     * @return string|null
     */
    public function getStatusReason()
    {
        return $this->container['statusReason'];
    }

    /**
     * Sets statusReason
     *
     * @param string|null $statusReason Detailed status reason.
     *
     * @return self
     */
    public function setStatusReason($statusReason)
    {
        if (is_null($statusReason)) {
            array_push($this->openAPINullablesSetToNull, 'statusReason');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('statusReason', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['statusReason'] = $statusReason;

        return $this;
    }

    /**
     * Gets contactId
     *
     * @return int|null
     */
    public function getContactId()
    {
        return $this->container['contactId'];
    }

    /**
     * Sets contactId
     *
     * @param int|null $contactId Associated contact ID.
     *
     * @return self
     */
    public function setContactId($contactId)
    {
        if (is_null($contactId)) {
            array_push($this->openAPINullablesSetToNull, 'contactId');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('contactId', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['contactId'] = $contactId;

        return $this;
    }

    /**
     * Gets initiatorId
     *
     * @return int
     */
    public function getInitiatorId()
    {
        return $this->container['initiatorId'];
    }

    /**
     * Sets initiatorId
     *
     * @param int $initiatorId ID of user who initiated the email.
     *
     * @return self
     */
    public function setInitiatorId($initiatorId)
    {
        if (is_null($initiatorId)) {
            throw new \InvalidArgumentException('non-nullable initiatorId cannot be null');
        }
        $this->container['initiatorId'] = $initiatorId;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


