<?php
/**
 * ScheduleEmailCampaignRequest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  TextMagic
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Textmagic API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.17.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace TextMagic\Models;

use \ArrayAccess;
use \TextMagic\ObjectSerializer;

/**
 * ScheduleEmailCampaignRequest Class Doc Comment
 *
 * @category Class
 * @package  TextMagic
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class ScheduleEmailCampaignRequest implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'scheduleEmailCampaign_request';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'emailSenderId' => 'int',
        'subject' => 'string',
        'message' => 'string',
        'fromName' => 'string',
        'replyToEmail' => 'string',
        'recipients' => '\TextMagic\Models\ScheduleEmailCampaignRequestRecipients',
        'scheduleParams' => '\TextMagic\Models\ScheduleEmailCampaignRequestScheduleParams'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'emailSenderId' => null,
        'subject' => null,
        'message' => null,
        'fromName' => null,
        'replyToEmail' => 'email',
        'recipients' => null,
        'scheduleParams' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'emailSenderId' => false,
        'subject' => false,
        'message' => false,
        'fromName' => true,
        'replyToEmail' => true,
        'recipients' => false,
        'scheduleParams' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'emailSenderId' => 'emailSenderId',
        'subject' => 'subject',
        'message' => 'message',
        'fromName' => 'fromName',
        'replyToEmail' => 'replyToEmail',
        'recipients' => 'recipients',
        'scheduleParams' => 'scheduleParams'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'emailSenderId' => 'setEmailSenderId',
        'subject' => 'setSubject',
        'message' => 'setMessage',
        'fromName' => 'setFromName',
        'replyToEmail' => 'setReplyToEmail',
        'recipients' => 'setRecipients',
        'scheduleParams' => 'setScheduleParams'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'emailSenderId' => 'getEmailSenderId',
        'subject' => 'getSubject',
        'message' => 'getMessage',
        'fromName' => 'getFromName',
        'replyToEmail' => 'getReplyToEmail',
        'recipients' => 'getRecipients',
        'scheduleParams' => 'getScheduleParams'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('emailSenderId', $data ?? [], null);
        $this->setIfExists('subject', $data ?? [], null);
        $this->setIfExists('message', $data ?? [], null);
        $this->setIfExists('fromName', $data ?? [], null);
        $this->setIfExists('replyToEmail', $data ?? [], null);
        $this->setIfExists('recipients', $data ?? [], null);
        $this->setIfExists('scheduleParams', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if (!is_null($this->container['subject']) && (mb_strlen($this->container['subject']) > 998)) {
            $invalidProperties[] = "invalid value for 'subject', the character length must be smaller than or equal to 998.";
        }

        if (!is_null($this->container['fromName']) && (mb_strlen($this->container['fromName']) > 500)) {
            $invalidProperties[] = "invalid value for 'fromName', the character length must be smaller than or equal to 500.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets emailSenderId
     *
     * @return int|null
     */
    public function getEmailSenderId()
    {
        return $this->container['emailSenderId'];
    }

    /**
     * Sets emailSenderId
     *
     * @param int|null $emailSenderId Email sender ID from your configured senders.
     *
     * @return self
     */
    public function setEmailSenderId($emailSenderId)
    {
        if (is_null($emailSenderId)) {
            throw new \InvalidArgumentException('non-nullable emailSenderId cannot be null');
        }
        $this->container['emailSenderId'] = $emailSenderId;

        return $this;
    }

    /**
     * Gets subject
     *
     * @return string|null
     */
    public function getSubject()
    {
        return $this->container['subject'];
    }

    /**
     * Sets subject
     *
     * @param string|null $subject Email subject line.
     *
     * @return self
     */
    public function setSubject($subject)
    {
        if (is_null($subject)) {
            throw new \InvalidArgumentException('non-nullable subject cannot be null');
        }
        if ((mb_strlen($subject) > 998)) {
            throw new \InvalidArgumentException('invalid length for $subject when calling ScheduleEmailCampaignRequest., must be smaller than or equal to 998.');
        }

        $this->container['subject'] = $subject;

        return $this;
    }

    /**
     * Gets message
     *
     * @return string|null
     */
    public function getMessage()
    {
        return $this->container['message'];
    }

    /**
     * Sets message
     *
     * @param string|null $message HTML email content.
     *
     * @return self
     */
    public function setMessage($message)
    {
        if (is_null($message)) {
            throw new \InvalidArgumentException('non-nullable message cannot be null');
        }
        $this->container['message'] = $message;

        return $this;
    }

    /**
     * Gets fromName
     *
     * @return string|null
     */
    public function getFromName()
    {
        return $this->container['fromName'];
    }

    /**
     * Sets fromName
     *
     * @param string|null $fromName Optional custom sender name.
     *
     * @return self
     */
    public function setFromName($fromName)
    {
        if (is_null($fromName)) {
            array_push($this->openAPINullablesSetToNull, 'fromName');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('fromName', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        if (!is_null($fromName) && (mb_strlen($fromName) > 500)) {
            throw new \InvalidArgumentException('invalid length for $fromName when calling ScheduleEmailCampaignRequest., must be smaller than or equal to 500.');
        }

        $this->container['fromName'] = $fromName;

        return $this;
    }

    /**
     * Gets replyToEmail
     *
     * @return string|null
     */
    public function getReplyToEmail()
    {
        return $this->container['replyToEmail'];
    }

    /**
     * Sets replyToEmail
     *
     * @param string|null $replyToEmail Optional custom reply-to email address.
     *
     * @return self
     */
    public function setReplyToEmail($replyToEmail)
    {
        if (is_null($replyToEmail)) {
            array_push($this->openAPINullablesSetToNull, 'replyToEmail');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('replyToEmail', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['replyToEmail'] = $replyToEmail;

        return $this;
    }

    /**
     * Gets recipients
     *
     * @return \TextMagic\Models\ScheduleEmailCampaignRequestRecipients|null
     */
    public function getRecipients()
    {
        return $this->container['recipients'];
    }

    /**
     * Sets recipients
     *
     * @param \TextMagic\Models\ScheduleEmailCampaignRequestRecipients|null $recipients recipients
     *
     * @return self
     */
    public function setRecipients($recipients)
    {
        if (is_null($recipients)) {
            throw new \InvalidArgumentException('non-nullable recipients cannot be null');
        }
        $this->container['recipients'] = $recipients;

        return $this;
    }

    /**
     * Gets scheduleParams
     *
     * @return \TextMagic\Models\ScheduleEmailCampaignRequestScheduleParams|null
     */
    public function getScheduleParams()
    {
        return $this->container['scheduleParams'];
    }

    /**
     * Sets scheduleParams
     *
     * @param \TextMagic\Models\ScheduleEmailCampaignRequestScheduleParams|null $scheduleParams scheduleParams
     *
     * @return self
     */
    public function setScheduleParams($scheduleParams)
    {
        if (is_null($scheduleParams)) {
            throw new \InvalidArgumentException('non-nullable scheduleParams cannot be null');
        }
        $this->container['scheduleParams'] = $scheduleParams;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


